ACTION_PICK_UP_LIVE_PILE = 52
ACTION_RESOLVE_NINE_DRAW = 53
ACTION_REVEAL_DRAW_PILE_TOP = 54
ACTION_END_PLAY_GROUP = 55

ACTION_FIX_SWAP_SLOT_0 = 56
ACTION_FIX_SWAP_SLOT_1 = 57
ACTION_FIX_SWAP_SLOT_2 = 58
ACTION_FIX_STACK_SLOT_0 = 59
ACTION_FIX_STACK_SLOT_1 = 60
ACTION_FIX_STACK_SLOT_2 = 61
ACTION_FIX_DONE = 62
ACTION_FIX_TAKE_FROM_STACK_SLOT_0 = 63
ACTION_FIX_TAKE_FROM_STACK_SLOT_1 = 64
ACTION_FIX_TAKE_FROM_STACK_SLOT_2 = 65
ACTION_FIX_KEEP_UNDERSIZED_HAND = 66

ACTION_FACE_DOWN_SLOT_0 = 67
ACTION_FACE_DOWN_SLOT_1 = 68
ACTION_FACE_DOWN_SLOT_2 = 69

ACTION_SPACE_SIZE = 70

FIX_SWAP_ACTIONS = {
    ACTION_FIX_SWAP_SLOT_0: 0,
    ACTION_FIX_SWAP_SLOT_1: 1,
    ACTION_FIX_SWAP_SLOT_2: 2,
}

FIX_STACK_ACTIONS = {
    ACTION_FIX_STACK_SLOT_0: 0,
    ACTION_FIX_STACK_SLOT_1: 1,
    ACTION_FIX_STACK_SLOT_2: 2,
}

FIX_TAKE_FROM_STACK_ACTIONS = {
    ACTION_FIX_TAKE_FROM_STACK_SLOT_0: 0,
    ACTION_FIX_TAKE_FROM_STACK_SLOT_1: 1,
    ACTION_FIX_TAKE_FROM_STACK_SLOT_2: 2,
}

FACE_DOWN_ACTIONS = {
    ACTION_FACE_DOWN_SLOT_0: 0,
    ACTION_FACE_DOWN_SLOT_1: 1,
    ACTION_FACE_DOWN_SLOT_2: 2,
}
